/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ControlEmpleados.Nomina;

import ControlEmpleados.AsistenciasEmpleados.frmVerAsistencia;
import ControlEmpleados.GestionEmpleados.frmGestionEmpleados;
import ControlEmpleados.frmMenuPrincipal;

/**
 *
 * @author Kelly
 */
public class frmGestionSalarios extends javax.swing.JFrame {

    /**
     * Creates new form frmGestionSalarios
     */
    public frmGestionSalarios() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolver = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnVolver1 = new javax.swing.JButton();
        btnVerNominas = new javax.swing.JButton();
        btnActualizarNomina = new javax.swing.JButton();
        btnRegistrarNomina = new javax.swing.JButton();
        btnRecibo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        btnVolver.setBackground(new java.awt.Color(102, 153, 255));
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/out50x50.png"))); // NOI18N
        btnVolver.setBorder(null);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(java.awt.SystemColor.activeCaption);

        jPanel2.setBackground(new java.awt.Color(102, 153, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gestion Salarios");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 276, 41));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Actualizar nomina");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, -1, -1));

        btnVolver1.setBackground(new java.awt.Color(102, 153, 255));
        btnVolver1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/out50x50.png"))); // NOI18N
        btnVolver1.setBorder(null);
        btnVolver1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolver1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 80, 90));

        btnVerNominas.setBackground(new java.awt.Color(102, 153, 255));
        btnVerNominas.setForeground(new java.awt.Color(102, 153, 255));
        btnVerNominas.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Downloads\\Buscar empleado y nmomina 120x120).png")); // NOI18N
        btnVerNominas.setBorder(null);
        btnVerNominas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerNominasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerNominas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 180, 130));

        btnActualizarNomina.setBackground(new java.awt.Color(102, 153, 255));
        btnActualizarNomina.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Downloads\\Actualizar nomina 120x120.png")); // NOI18N
        btnActualizarNomina.setBorder(null);
        btnActualizarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarNominaActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizarNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 180, 150));

        btnRegistrarNomina.setBackground(new java.awt.Color(102, 153, 255));
        btnRegistrarNomina.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Downloads\\registrar nomina 120x120.png")); // NOI18N
        btnRegistrarNomina.setBorder(null);
        btnRegistrarNomina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarNominaActionPerformed(evt);
            }
        });
        jPanel2.add(btnRegistrarNomina, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 180, 130));

        btnRecibo.setBackground(new java.awt.Color(102, 153, 255));
        btnRecibo.setIcon(new javax.swing.ImageIcon("C:\\Users\\anton\\Downloads\\Generar recibo 120x120.png")); // NOI18N
        btnRecibo.setBorder(null);
        btnRecibo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReciboActionPerformed(evt);
            }
        });
        jPanel2.add(btnRecibo, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 220, 150));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Ver Salarios");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Generar recibo");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Volver");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Registrar nomina");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();  // Cierra el formulario actual
        frmMenuPrincipal frame = new frmMenuPrincipal();
        frame.setVisible(true);
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnVolver1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolver1ActionPerformed
        // TODO add your handling code here:
         this.dispose();  // Cierra el formulario actual
        frmMenuPrincipal frame = new frmMenuPrincipal();
        frame.setVisible(true);
    }//GEN-LAST:event_btnVolver1ActionPerformed

    private void btnVerNominasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerNominasActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmVerNominas verNominas = new frmVerNominas();
        verNominas.setVisible(true);
        verNominas.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVerNominasActionPerformed

    private void btnReciboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReciboActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmGenerarRecibo  NominaRecibo = new frmGenerarRecibo();
        NominaRecibo.setVisible(true);
        NominaRecibo.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnReciboActionPerformed

    private void btnActualizarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarNominaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmActualizarNomina  actualizarNOMINA = new frmActualizarNomina();
        actualizarNOMINA.setVisible(true);
        actualizarNOMINA.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnActualizarNominaActionPerformed

    private void btnRegistrarNominaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNominaActionPerformed
        // TODO add your handling code here:
        this.dispose();
        frmRegistrarNomina  registrarNOMINA = new frmRegistrarNomina();
        registrarNOMINA.setVisible(true);
        registrarNOMINA.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnRegistrarNominaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGestionSalarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGestionSalarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGestionSalarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGestionSalarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGestionSalarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarNomina;
    private javax.swing.JButton btnRecibo;
    private javax.swing.JButton btnRegistrarNomina;
    private javax.swing.JButton btnVerNominas;
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton btnVolver1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
